In [2]:
import pandas as pd
import numpy as np
import json
def get_json(country):
    url='google'
    countries=pd.read_csv('tsv/products_countries.tsv','\t')
    products=pd.read_csv('tsv/products.tsv','\t',low_memory=False)[['code','name']]
    additives=pd.read_csv('tsv/products_additives.tsv','\t')
    d=pd.merge(countries[countries['country']==country],pd.merge(products,additives,how='inner',left_on='code',right_on='code'),how='inner',left_on='code',right_on='code')[['code','name','additive']]
    data=[]
    groups=d.groupby('additive')
    for name,g in groups:
        additive=dict({})
        additive['name']=name
        additive['count']=g.shape[0]
        additive['key']=name
        pages=[]
        for i,p in g.iterrows():
            product=dict({})
            product['name']=p['name']
            product['key']=p['code']
            product['title']=p['name']
            product['url']=url+p['code']
            pages.append(product)
        additive['pages']=pages
        data.append(additive)
    return json.dumps(data)
# print(get_json('lebanon'))

In [3]:
data=pd.read_csv('tsv/products.tsv','\t',low_memory=False)

In [4]:
data.head()

,code,name,image,n_additives,nutriscore,nova,energy_100g,energy-from-fat_100g,fat_100g,saturated-fat_100g,...,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g,choline_100g,phylloquinone_100g,beta-glucan_100g,inositol_100g,carnitine_100g
0,0000000001281,Tarte noix de coco,NaN,0,d,NaN,1594.0,NaN,22.0,15.5,...,NaN,14.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0000000001885,Compote de poire,NaN,0,a,NaN,657.0,NaN,0.0,0.0,...,NaN,-2.0,-2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0000000005241,Bagel,NaN,0,b,NaN,824.0,NaN,5.0,1.1,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0000000005470,BAguette bressan,NaN,3,a,4.0,669.0,NaN,2.2,0.5,...,NaN,-4.0,-4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0000000005661,Pavé de saumon fumé à la ficelle,NaN,0,d,NaN,1059.0,NaN,17.0,2.6,...,NaN,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
pd.DataFrame((data.isnull()).sum(axis = 0)).sort_values(by=0)

                                           0
code                                       0
n_additives                                0
name                                     469
energy_100g                            24303
proteins_100g                          25035
fat_100g                               25831
carbohydrates_100g                     26109
sugars_100g                            27896
saturated-fat_100g                     28401
salt_100g                              29662
sodium_100g                            29665
nova                                   36479
nutrition-score-fr_100g                38020
nutriscore                             38020
nutrition-score-uk_100g                38020
fiber_100g                            100187
image                                 112786
fruits-vegetables-nuts-estimate_100g  171655
calcium_100g                          171752
alcohol_100g                          172549
vitamin-c_100g                        174625
iron_100g                             174723
cocoa_100g                            175610
vitamin-a_100g                        175610
cholesterol_100g                      175988
trans-fat_100g                        176045
polyunsaturated-fat_100g              176325
monounsaturated-fat_100g              176361
fruits-vegetables-nuts_100g           176480
vitamin-b1_100g                       177492
...                                      ...
carbon-footprint_100g                 179124
starch_100g                           179127
collagen-meat-protein-ratio_100g      179156
copper_100g                           179197
omega-6-fat_100g                      179200
manganese_100g                        179217
selenium_100g                         179246
bicarbonate_100g                      179257
fluoride_100g                         179280
vitamin-k_100g                        179298
caffeine_100g                         179312
ph_100g                               179335
silica_100g                           179375
taurine_100g                          179393
folates_100g                          179409
casein_100g                           179412
molybdenum_100g                       179415
chromium_100g                         179415
omega-9-fat_100g                      179417
inositol_100g                         179417
beta-carotene_100g                    179421
serum-proteins_100g                   179423
choline_100g                          179424
carnitine_100g                        179434
beta-glucan_100g                      179435
nucleotides_100g                      179438
chlorophyl_100g                       179445
glycemic-index_100g                   179445
water-hardness_100g                   179446
phylloquinone_100g                    179447

[78 rows x 1 columns]

In [ ]:
data.shape

In [10]:
x=data[['code','energy_100g','n_additives','proteins_100g','fat_100g','carbohydrates_100g','sugars_100g','saturated-fat_100g','salt_100g','sodium_100g']]

In [9]:
x=x.fillna(x.mean())

In [ ]:
x.

In [ ]:
%matplotlib inline
from matplotlib import pyplot as plt

In [ ]:
x.plot(y=['energy_100g'])

In [ ]:
plt.plot(x.sort_values(by='proteins_100g').dropna()['proteins_100g'])

In [ ]:
x=data[['n_additives','proteins_100g','fat_100g','carbohydrates_100g','sugars_100g','saturated-fat_100g','salt_100g','sodium_100g']].head(200)(pd.DataFrame(x.sort_values(by='proteins_100g')).dropna().reset_index()).plot()

In [37]:
def get_products_info(country):
    countries=pd.read_csv('tsv/products_countries.tsv','\t',low_memory=False)
    products_in_country=pd.DataFrame(countries[countries['country']==country]['code'])
    product=pd.read_csv('tsv/products.tsv','\t',low_memory=False)[['code','energy_100g','n_additives','proteins_100g','fat_100g','carbohydrates_100g','sugars_100g','saturated-fat_100g','salt_100g','sodium_100g']]
    product=products_in_country.merge(x,left_on='code',right_on='code')
    print(product)

In [11]:
countries=pd.read_csv('tsv/products_countries.tsv','\t',low_memory=False)

In [21]:
s=pd.DataFrame(countries[countries['country']=='lebanon'].head()['code'])

In [22]:
ss=s.merge(x,left_on='code',right_on='code')

In [23]:
ss

,code,energy_100g,n_additives,proteins_100g,fat_100g,carbohydrates_100g,sugars_100g,saturated-fat_100g,salt_100g,sodium_100g
0,0022314020123,439.0,0,1.7,1.2,20.0,4.0,0.44,0.01000,0.003937
1,0735143003044,544.0,1,10.0,0.5,NaN,2.0,0.00,1.32080,0.520000
2,0735143009145,2874.0,0,25.4,58.8,12.7,2.1,12.30,0.00000,0.000000
3,0744171120135,583.0,0,0.0,0.0,22.2,0.0,0.00,1.91000,0.750000
4,0788930201123,272.0,0,0.0,0.0,16.0,13.0,0.00,0.00762,0.003000

In [30]:
get_products_info('france')

,code,energy_100g,n_additives,proteins_100g,fat_100g,carbohydrates_100g,sugars_100g,saturated-fat_100g,salt_100g,sodium_100g
0,0000000001281,1594.0,0,4.60,22.00,27.30,21.90,15.50,0.1000,0.039370
1,0000000001885,657.0,0,0.60,0.00,36.00,27.00,0.00,0.0000,0.000000
2,0000000005241,824.0,0,8.40,5.00,28.70,3.00,1.10,0.4670,0.183858
3,0000000005470,669.0,3,9.50,2.20,25.20,0.60,0.50,0.3580,0.140945
4,0000000005661,1059.0,0,23.00,17.00,0.50,0.50,2.60,2.5000,0.984252
5,000000001772,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0000000020114,0.0,1,0.00,0.00,0.00,0.00,0.00,NaN,NaN
7,0000000125512,2427.0,0,3.00,38.00,58.00,58.00,36.00,0.5000,0.196850
8,0000000274722,450.0,2,6.80,2.20,15.30,0.50,0.90,0.7000,0.275591
9,0000000274739,455.0,0,4.40,4.20,12.50,1.40,2.10,0.6000,0.236220
10,0000000491228,1952.4,4,6.80,15.30,75.50,69.80,11.20,0.5000,0.196850
11,0000005200016,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,0000007020254,213.0,3,0.00,0.00,14.00,0.00,0.00,1.0000,0.393701
13,0000007730009,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,0000007818707,201.0,3,0.00,0.00,13.30,12.70,0.00,0.0500,0.019685
15,0000009125124,1577.0,1,1.50,0.50,93.00,66.00,0.10,0.0200,0.007874
16,0000009336247,1674.0,7,0.00,0.00,93.30,93.30,0.00,0.0000,0.000000
17,0000010068175,17.0,0,0.10,0.10,0.10,0.10,0.10,0.0010,0.000394
18,0000010090206,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,0000010127735,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,0000010150917,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,0000010166604,1749.0,0,4.29,10.41,77.68,70.54,0.79,0.2100,0.082677
22,0000010166697,1732.0,8,4.20,10.29,77.02,69.97,0.77,0.2100,0.082677
23,0000010206515,1720.0,5,0.03,6.42,87.86,81.67,3.53,0.1000,0.039370
24,0000010216477,1644.0,0,0.00,4.80,87.10,84.70,3.30,0.1200,0.047244
25,0000010216491,1644.0,0,0.00,4.80,87.10,84.70,3.30,0.1200,0.047244
26,0000018927207,1682.0,0,4.30,5.20,2.40,1.90,0.40,10.0000,3.937008
27,0000020004552,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,0000023019027,1427.0,0,4.30,17.00,43.00,14.00,9.90,0.8900,0.350394
29,0000026061993,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
145717,9772752170485,117.0,0,5.20,25.00,51.00,29.00,5.80,0.3800,0.149606
145718,9778564312457,2155.0,0,7.80,NaN,NaN,1.80,3.40,1.3500,0.531496
145719,9780221379642,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145720,9780545789646,735.0,0,0.00,0.00,13.00,6.20,0.00,0.0000,0.000000
145721,9780546379648,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145722,9782253187851,1494.0,8,18.00,3.80,62.00,20.00,0.70,0.0000,0.000000
145723,9783822833292,4.0,0,1.00,1.00,1.00,1.00,1.00,1.0000,0.393701
145724,9791463741241,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145725,9800460306008,1523.0,0,10.00,36.00,0.50,0.50,25.00,1.0000,0.393701
145726,9805508002508,180.0,0,0.10,0.00,10.70,10.10,0.00,0.0100,0.003937
145727,98152056,1703.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145728,9866670004943,213.0,0,0.50,0.00,12.00,12.00,0.00,0.0000,0.000000
145729,9876754344551,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145730,9900000000226,2629.0,0,14.95,60.75,16.70,4.34,4.46,0.0000,0.000000
145731,9900000000325,1469.0,0,20.50,5.85,47.50,6.50,0.55,0.0800,0.031496
145732,9900000001926,1017.0,7,3.00,11.00,32.00,24.00,4.50,0.0400,0.015748
145733,9900000002237,615.0,0,0.00,0.00,87.00,28.00,0.00,0.0100,0.003937
145734,9900010011557,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145735,99020118,1247.0,0,19.00,24.00,2.00,NaN,18.00,1.0000,0.393701
145736,9906410000009,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145737,9909206000009,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145738,9910128446592,2498.0,0,30.00,50.00,7.00,3.60,6.80,0.0200,0.007874
145739,99111250,21.0,0,0.50,0.20,0.50,0.50,0.20,0.0254,0.010000
145740,9935010000003,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145741,9955100109478,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145742,9985023697844,1464.0,0,4.20,2.10,78.00,60.00,0.50,0.0800,0.031496
145743,9991111111154,285.0,1,2.00,0.20,14.00,14.00,0.00,0.0000,0.000000
145744,9996980313319,351.0,0,1.80,3.80,10.20,0.50,2.00,1.0000,0.393701
145745,9998070000000,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145746,9999900002553,2443.0,0,7.60,46.90,30.70,26.90,28.20,0.0300,0.011811

In [36]:
print(x.head())

            code  energy_100g  n_additives  proteins_100g  fat_100g  \
0  0000000001281       1594.0            0            4.6      22.0
1  0000000001885        657.0            0            0.6       0.0
2  0000000005241        824.0            0            8.4       5.0
3  0000000005470        669.0            3            9.5       2.2
4  0000000005661       1059.0            0           23.0      17.0

   carbohydrates_100g  sugars_100g  saturated-fat_100g  salt_100g  sodium_100g
0                27.3         21.9                15.5      0.100     0.039370
1                36.0         27.0                 0.0      0.000     0.000000
2                28.7          3.0                 1.1      0.467     0.183858
3                25.2          0.6                 0.5      0.358     0.140945
4                 0.5          0.5                 2.6      2.500     0.984252